### ISSUE TITLE
How can I help

### ISSUE THREAD

**Issue by r9mp** [MasteringNuxt/NuxtBnB#1]
Hi there!
I'm a NuxtJS freelance with no mission atm.
I puchased "Mastering Nuxt". Still basic and way too short, but the content is qualitative and promising!!
How can I help?

**Comment by sarfarazengglb** [comment]
This too basic i was expecting more

**Comment by iAmXquisite** [comment]
It is pretty basic but I am new to Front End Development so i'm hoping this can jumpstart me.

**Comment by sarfarazengglb** [comment]
I think we need to have JAM Stack or FIrebase or Any fullstack. 
We should in include 
Auth - BuiltIn and Cloud (Amazon Cognito, Azure AD)
Backend - Express or Strapi or Other backend

**Comment by kgnfth** [comment]
See they only care about money
they never answer or help someone

**Comment by RaoulKoenig** [comment]
I also regret buying this course.

**Comment by muxame** [comment]
The course is nice.

I bought it i learned new things from it .
But sure should buy other courses from udemy too to support my leering.....

I tried to support the team by buying this course I sent my comments via
email about this course.  Never got a reply! Sadly seams the this team not
taking building thier community seriously...


I am not thinking to get a refund as I respect the efforts they put into
building this course .

Sure they need to step-up thier community engagement and support.

Sure the course content should be more engaging.

One course I bought from udemy for less than 15$ has great valuable
content. But every instructor has his own way .

Sometime I feel the instructor skip valuable content explanation for
example :-

At module :- Disabling Prefetch Globally

It was really advanced topic and nothing explained in details with it at
the end instructor left it up to you to go and read ..i hope at future
updates they consider giving nice real-time example for such important
modules such as hooks too... tailwind,firebase real-time db, and  UI/UX
etc... this what going to distinguish this course from other cocuses

Building the UI is so interesting part looking forward to watch it . I hope
this instructor teach us real valuable information at this section and
making interesting and not to rush things .

Thanks
Muhannad

**Comment by drinkredwine** [comment]
Me too. It's more of a scam than a serious offer.

**Comment by prakashpie** [comment]
How to get refund?

**Comment by lustremedia** [comment]
To get refunded you need to ask for a refund via the payment method I believe, within 2weeks or so after booking the course. I did so and got refunded.

**Comment by larsdouweschuitema** [comment]
They clearly stated on the website that the course is outlined and that they will add lessons progressively.
The quality is really good and not sure why you would refund just because it's in progress. You are also directly supporting the Nuxt.js framework because 25% of sales goes into the development of the Nuxt.js framework.
Support this great open source project ;)

**Comment by prakashpie** [comment]
> They clearly stated on the website that the course is outlined and that they will add lessons progressively.
> The quality is really good and not sure why you would refund just because it's in progress. You are also directly supporting the Nuxt.js framework because 25% of sales goes into the development of the Nuxt.js framework.
> Support this great open source project ;)

Fine then i am not cancelling. Although i was expecting a little bit more advanced but as you said, it is going good for now.

**Comment by BibekStha** [comment]
Although the course progress is slow for many (not an issue for me personally, due to many other factors),
what I have learned till now is of high quality. We are learning from a very experienced developer (around 35 years of experience) and his way of explaining concepts is also very good. These reasons alone will make me stick with the course.
And as mentioned by @larsdouweschuitema, we help the Nuxt.js framework development directly by buying this course.

**Comment by sarfarazengglb** [comment]
The teacher is experienced developer and i think we should be patience and add materials. Nuxt is new and exciting technology. We can also contribute to the project and built community.  As its Pandemic we don't know what situation team is facing.

Let's hope good
