### ISSUE TITLE
sass-loader incompatible with version of webpack

### ISSUE THREAD

**Issue by jonasmit** [MasteringNuxt/NuxtBnB#10]
In the Working with Styles --> Setting Up the Design Lesson, the instructions demonstrate adding sass-loader which appears to be incompatible with webpack.

12.1.0 is installed when doing yarn add --dev sass sass-loader

I had to grab the package.json file from the repo and use 10.1.1 to get a version of sass-loader that would work...

Not sure if there is a better strategy to get a compatible version of all the packages...

**Comment by hecktarzuli** [comment]
Other than providing this repo with a known good yarn.lock file, I'm not sure either!  Since everyone is adding these libs as they go, and are on different environments with different versions it's tough.
