### ISSUE TITLE
Video doesn't include create command

### ISSUE THREAD

**Issue by piknikki** [MasteringNuxt/NuxtBnB#11]
Students probably don't know how you created the app, since this command is skipped, if they haven't tried nuxt before.

Getting Started section >> How to Create a New Nuxt Project From Scratch >> around 33 seconds into video, the project is created, but the last command instructor performed was `yarn add nuxt`. Should probably show something like `npx create nuxt-app NuxtBnB`

**Comment by fitzage** [comment]
The instructor didn't use the create nuxt app methods, but started from scratch and imported nuxt. It's truly being created from scratch, which means later we have to manually add things like the config to enable auto-importing of components.

**Comment by hecktarzuli** [comment]
We started from scratch so we could introduce functionalities, folders, configs etc.. as we progressed and to demonstrate you don't even need a config to get started.  The idea was to deeply understand how each of these things worked and how to control the behavior vs a bunch of things the template did for you.
