### ISSUE TITLE
Repo not working 

### ISSUE THREAD

**Issue by dhavalkakkad** [MasteringNuxt/NuxtBnB#12]
Hi there, 

I have purchased the Nuxt course and came to this repo. I am trying to clone this in my local machine but it gives me some copy file errors.

Btw, I am running after cloning. sudo npm install. 
my npm version is the latest. I am using Mac. 

![Screenshot 2021-08-18 at 12 58 25 PM](https://user-images.githubusercontent.com/8214362/129856374-7948c490-eefc-4552-801f-62824e8dc368.png)
. Screenshot attached. 

Please help me. thanks

**Comment by OsoThevenin** [comment]
If you follow the course the instuctor uses yarn to install all the dependencies.
Try to run `yarn install`

**Comment by dhavalkakkad** [comment]
@OsoThevenin thanks for your comment. I will try that out and let you know if I will have any issues. cheers

**Comment by hecktarzuli** [comment]
This looks to be a local permission problem.
