### ISSUE TITLE
Depreciation of Google Sign-in Javascript Library

### ISSUE THREAD

**Issue by softwaredeveloptam** [MasteringNuxt/NuxtBnB#13]
Seems like Google will disconnect the [Google Sign-in Javascript Platform Library](https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html) on March 31st, 2023 to use their new [Google Identity Services SDK](https://developers.googleblog.com/2021/07/launching-our-new-google-identity-services-apis.html) for the future. 

It's a bit far into the future as the time of this post but thought I mention it for future users that will be following step by step in creating the NuxtBnB app.

**Comment by mjknoxie** [comment]
any chance this is being looked at? The code as presented now throws an uncaught exception 


```
cb=gapi.loaded_0?le=scs:224 Uncaught 
{error: 'idpiframe_initialization_failed', details: 'You have created a new client application that use…i/web/guides/gis-migration) for more information.'}
details: "You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."
error: "idpiframe_initialization_failed"
```

**Comment by archer-john** [comment]
This is now a problem when trying to follow along, all new clients are forced to use the new identity services. Is there a plan to update this module?

**Comment by kubarazny** [comment]
No. They should stop selling this course, because its not working!

**Comment by Toryn02** [comment]
What an utter joke this course has been since it was first released.  It
took well over six months for them to fully build it out after they started
selling it at such a premium price point; they short-changed the final
build and it's not even a fully working website even before the code breaks
(there are plenty of FULL AirBnB clone builds on YouTube for free that go
way deeper than this course does); and now the code is broken and they're
radio silent about fixing it.  VueSchool will never, ever get another dime
of my money.

**Comment by hecktarzuli** [comment]
Interesting that all `new` clients would require this.  When I first saw a report about something similar I couldn't re-create it, but that's likely since my accounts already existed.  I'll dig.

**Comment by hecktarzuli** [comment]
This turned out to be pretty easy.  The gist is a slight tweak in the template, and google gives you the user info inside the JWT now instead of via a separate lib.

https://github.com/MasteringNuxt/NuxtBnB/pull/20/files
