### ISSUE TITLE
Vercel deployment not working

### ISSUE THREAD

**Issue by rowild** [MasteringNuxt/NuxtBnB#15]
As the title says...

**Comment by coxlr** [comment]
Try adding the following to the package.json file, this allowed me to be able to deploy on Vercel

```
  "resolutions": {
    "sharp": "0.28.0"
  },
```

**Comment by wandarkaf** [comment]
In my case, on December 1st 2021, you need to let Vercel know that `sharp` is a dev dependency on the `package,json`: 
```
{
  ...
  "devDependencies": {
    ...
     "sharp": "0.27.0"
  }
  ...
}
```

Vercel use `node 14.X`, so sharp `0.28.0` cause issue on deploy, because is not compatible with the latest node version.

Hope it helps 👍🏼 .

**Comment by hecktarzuli** [comment]
I've added node 14.x to the package.json file to force node 14 in vercel.
