### ISSUE TITLE
Cannot find module '~/utils/pluralize'

### ISSUE THREAD

**Issue by garbinmarcelo** [MasteringNuxt/NuxtBnB#16]
Hello I'm in the vide class "Styling the Property Page (Part 1)", but when I got to the part of separating the plurilize method I got the following error:

`Cannot find module '~/utils/pluralize'`

![image](https://user-images.githubusercontent.com/9335588/134732548-72cf6fe3-057b-407a-a825-2555eb1fb958.png)

It appears to be a babel-loader related issue.

Anyone gone through this could help?

I'm using nuxt@2.15.8

Thanks

**Comment by ktiedt** [comment]
If you just created the utils folder, new folders often require restarting the dev environment... have you tried that?

**Comment by garbinmarcelo** [comment]
> If you just created the utils folder, new folders often require restarting the dev environment... have you tried that?

Yes, I did.

At the terminal the return is:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                  friendly-errors 17:25:34

This dependency was not found:                                                                                                                                                           friendly-errors 17:25:34
                                                                                                                                                                                         friendly-errors 17:25:34
* ~/utils/pluralize in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/PropertyDetails.vue?vue&type=script&lang=js&             friendly-errors 17:25:34
                                                                                                                                                                                         friendly-errors 17:25:34
To install it, you can run: npm install --save ~/utils/pluralize
```

![image](https://user-images.githubusercontent.com/9335588/134735602-b7d059f0-7311-4c7f-aaa3-b6c08e48f297.png)

I have no idea what it could be. :confused:

**Comment by garbinmarcelo** [comment]
My fault.

File name error, was like "plurilize.js". It would never work. :flushed: :sweat_smile:

Sorry and thanks for the feedback.
