### ISSUE TITLE
yarn add nuxt - does not create files in folder

### ISSUE THREAD

**Issue by tekspirit** [MasteringNuxt/NuxtBnB#17]
re: How to Create a New Nuxt Project From Scratch

On a mac, if I go to my nuxtbnb folder and type 'yarn add nuxt', it updates nuxt on the system but does not create any files in the nuxtBnB folder.  Is the command accurate?

**Comment by Krislunde** [comment]
Try 
`yarn create nuxt-app <project-name>`

**Comment by tekspirit** [comment]
is this going to be a responsive web app or single page app? (maybe any important settings when you run yarn create nuxt-app <project name> as there are a bunch of parameters to select.

**Comment by wandarkaf** [comment]
I believe the end goal of the course is to create a `nuxt` app from scratch. So `yarn add nuxt` just do that, add a `nuxt` dependency on the `nuxtBnB` folder, on the `node_modules` folder. If you use `yarn create nuxt-app <project-name>`, you will create a nuxt template project, with a lot pre made configuration and best practices. 

To wrap up: 

- `yarn add nuxt` adds a nuxt dependency in you folder.
- `yarn create nuxt-app <project-name>` creates a new nuxt project, based on a pre build configuration.
