### ISSUE TITLE
New course video release schedule?

### ISSUE THREAD

**Issue by Toryn02** [MasteringNuxt/NuxtBnB#2]
Hi there,

I just purchased the Mastering Nuxt course, and while I understood that the course wasn't yet finished, frankly I expected much more than twelve short lessons that so far only walk through the basics of Nuxt routing and creating our first pages.  There are high-quality Udemy courses that are 10+ hours of in-depth Nuxt content taught by experienced Nuxt developers and often available for sale at just $10.

I'd very much appreciate an update on when the remaining videos for this course are scheduled to be released.  I don't mind being an early adopter, but at this price point and with this current amount of content, I'm really struggling to see the value in what I just purchased.

Thank you,
Josh

**Comment by RaoulKoenig** [comment]
I also expected significantly more at this price.

I can recommend Maximilian Schwarzmüller on Udemy – or – Vue Mastery is really good too.

I ordered the more expensive "Complete" course from Mastering Nuxt ... but what I've seen (by now) is ridiculous.

**Comment by BibekStha** [comment]
From what I know, the structure and content of the course has already been finalized. The actual course videos will be created and posted gradually.

But a schedule for that would definitely be great.

**Comment by tcimawap** [comment]
+1 : please provide course video release schedule and a way for us to be confident regarding the content to come value...

**Comment by yalondpsi** [comment]
I am in the same opinion,
The course content is lame. There are so few lessons without no real value regarding the price!

**Comment by lustremedia** [comment]
I am also a bit disappointed from the content so far at that price. I have taken both courses by Maximilian Schwarzmüller on udemy and I really hoped this course would be more in depth. I am sure there is more to come but I want at least an overview of what is covered, otherwise a refund would be in order.

174 USD is no joke to most of us here ...

**Comment by drewbaker** [comment]
100% agree with the above comments. Knew this was unfinished, but surprised to see it so incomplete. 

If the “course outline” is complete, then tell us what that is and when.

**Comment by everylastpixel** [comment]
I have to agree with everyone here. Not to at least have a detailed schedule of what is coming up (and when) is really unprofessional. I've paid my money and now just have to wait for content to arrive with no idea of when that will happen...

**Comment by parleweb** [comment]
Same opinion.

**Comment by moisessepulveda** [comment]
I already finished the existing content, I'd really appreciate to know what is coming, also any kind of answers from NuxtMastery related to this topic would be really helpful. It looks like you launched a course with no clear path, no course begins in this way, at least not a payed one.

**Comment by hootlex** [comment]
Thanks everyone for the feedback and your support.

As most of you know the course is currently in development and we will be releasing all lessons progressively until the course is complete.

Publishing a release schedule is one of our top priorities right now and we're aiming to have it online in 1 - 2 weeks at the latest.

For other issues and feedback, please reach out to team@masteringnuxt.com

**Comment by Toryn02** [comment]
Alex, my original issue request was for the Mastering Nuxt team to provide an outline or schedule for the upcoming videos to be released as part of the course.  I'd very much appreciate it if you kept this issue open until that outline or schedule has been released.

I also very much hope that your team can provide that outline before the end of the two-week course trial period, so that we can realistically assess whether the promised future content will warrant the premium price that you've placed on this course.  Thank you.

**Comment by RaoulKoenig** [comment]
Simply closing this issue upsets me – if there are no news I will cancel next week.
I'll have to check, when my two-weeks started.

**Comment by hootlex** [comment]
@Toryn02 @RaoulKoenig 

Thanks for the feedback.

> I also very much hope that your team can provide that outline before the end of the two-week course trial period, so that we can realistically assess whether the promised future content will warrant the premium price that you've placed on this course.

We have escalated this topic with the team and we are hoping to have the outline publicly available early this week so you have enough time to evaluate.

> Alex, my original issue request was for the Mastering Nuxt team to provide an outline or schedule for the upcoming videos to be released as part of the course. I'd very much appreciate it if you kept this issue open until that outline or schedule has been released.

This GitHub repository is for tracking issues related to the NuxtBnB codebase. 

This issue ([#2](https://github.com/MasteringNuxt/NuxtBnB/issues/2)) is not related to NuxtBnB codebase and thus I have closed it. Currently such matters should be discussed on the Mastering Nuxt Discord server or via email to team@masteringnuxt.com.

**Comment by Toryn02** [comment]
Okay, then I'll look for the full course outline to be uploaded to Discord early this week. Thank you.

**Comment by Huazo** [comment]
Whats the discord link
