### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Fudra** [MasteringNuxt/NuxtBnB#3]
Is there a link or an invitation to a discord server? During the registration process i've got none invitation link.

**Comment by BibekStha** [comment]
I got my Discord invitation through email yesterday, which was a couple of days after I actually bought the course.
Yours might be on the way too.

**Comment by hootlex** [comment]
@Fudra All pending Discord invites were sent out yesterday. Can you confirm you've received it?

For any issue you might face, please reach out to our support team at team@masteringnuxt.com

**Comment by Fudra** [comment]
@hootlex  I've received the Invitation and already joined. Thank you!
