### ISSUE TITLE
Please fix video URL for lesson 57 (aka "Stripe Webhooks")

### ISSUE THREAD

**Issue by bkuri** [MasteringNuxt/NuxtBnB#8]
The following URL throws an `ERR_INVALID_RESPONSE` error:

https://api.masteringnuxt.com/lessons/57/download/sd (stripped personal params just in case)

Hope this helps!

**Comment by bkuri** [comment]
Just tried again and the error persists. Hope this can be fixed soon. Thanks.

**Comment by mrjdomingus** [comment]
I second this request, the above URL is used by the **Download video** button of [https://masteringnuxt.com/lessons/stripe-webhooks](https://masteringnuxt.com/lessons/stripe-webhooks)

**Comment by hecktarzuli** [comment]
This is fixed!
